### ISSUE TITLE
Pull Request by first time contributors are merged automatically

### ISSUE THREAD

**Issue by Talinx** [framewiki/framewiki.net#41]
The [Contributing](https://framewiki.net/framewiki:contributing#how-to-publish-your-changes) page mentions that

> The first time you contribute, an editor, maintainer or admin will need to approve your changes.

However, [my first PR](https://github.com/framewiki/framewiki.net/pull/40) was merged without any manual approval as far as I can tell.

**Comment by Morpheus636** [comment]
That was a GitHub-based restriction that I had been trying to get around. Sounds like switching to the pull-request-target trigger for the auto-merge system did so! I will update the documentation shortly.
