### ISSUE TITLE
The image in the top left is inverted when dark mode is enabled and the window is <= 992 pixels wide.

### ISSUE THREAD

**Issue by RiftBladeMc** [framewiki/framewiki.net#63]
When dark mode is enabled the image in the top left has inverted coloring.

Attached images show the inverted coloring.

![framewikiscreenshot1](https://github.com/framewiki/framewiki.net/assets/41810843/32d277ac-a3a8-4f29-9fe1-f008f03e7233)

![image0](https://github.com/framewiki/framewiki.net/assets/41810843/15591569-8658-4e30-ac10-90de96758df4)

**Comment by Morpheus636** [comment]
That PR didn't actually fix this and has been reverted. Fixed in https://github.com/framewiki/git-wiki-theme/commit/c5c68c1662dacce6a0c8cb8adeb1688ff20a3c0a
