### ISSUE TITLE
Significant wasted space on windows ranging from 961 to 992 pixels wide (inclusive).

### ISSUE THREAD

**Issue by RiftBladeMc** [framewiki/framewiki.net#64]
A significant blank space appears when viewed in a window between 961 and 992 pixels wide.

Webpage at 961 pixels wide:

![961](https://github.com/framewiki/framewiki.net/assets/41810843/4fdba077-b1d5-46a6-a4d4-103003691455)

Webpage at 960 pixels wide:

![960](https://github.com/framewiki/framewiki.net/assets/41810843/7660f45b-4184-42a3-9e15-b139221a3e12)

**Comment by Morpheus636** [comment]
Should be fixed as of https://github.com/framewiki/git-wiki-theme/commit/9b7dfceae8a4bf92dbf46f7b592009745e5dd5d8

**Comment by Morpheus636** [comment]
Confirmed fixed via rebuild.
